### ISSUE TITLE
problem with library's creation on mac

### ISSUE THREAD

**Issue by rv33** [modmido/psiquasp#2]
Hello

Many thanks to the developpers to make this library available.

I have some issues though with its compilation. After having successfully installed petsc and sepc on my mac (macOS High Sierra version 10.13.4), I changed the options in the options.mk file and run the make file in the psiquasp directory; here is the response to the make command

---
Building PsiQuaSP library

   Compiling src/index.cpp with optimizations

In file included from index.cpp:14:

In file included from ./../include/index.hpp:16:

In file included from ./../include/system.hpp:114:

In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/sstream:174:

In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:138:

In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:

In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:18:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/mutex:495:26: error: expected expression

        __execute(_Index());

                         ^

1 error generated.

Failure while executing command: /Users/vallee/Qsoft/petsc/arch-darwin-c-debug/bin/mpicc -std=c++0x -O0 -g -Wall -c index.cpp -I/Users/vallee/Qsoft/petsc/include -I/Users/vallee/Qsoft/petsc/arch-darwin-c-debug/include -Wl,-rpath,/Users/vallee/Qsoft/petsc/arch-darwin-c-debug/lib -L/Users/vallee/Qsoft/petsc/arch-darwin-c-debug/lib -Wl,-rpath,/Users/vallee/Qsoft/petsc/arch-darwin-c-debug/lib -Wl,-rpath,/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0 -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0 -Wl,-rpath,/usr/local/gfortran/lib -L/usr/local/gfortran/lib -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin -lpetsc -lflapack -lfblas -lstdc++ -ldl -lmpifort -lmpi -lpmpi -lgfortran -lSystem -lgcc_ext.10.5 -lquadmath -lm -lc++ -ldl -lmpicxx -lmpi -lpmpi -lSystem -lclang_rt.osx -lstdc++ -ldl

make[1]: *** [index.o] Error 1

Do you have any idea of what can be wrong?

Thanks in advance for your answer :-)

**Comment by modmido** [comment]
Hello,
thank you for reporting this problem. 
There seems to be a problem with the apple c++ environment and PsiQuaSP, in particular the mutex library. This error can be fixed by setting the compiler flag to '-std=c++98' instead of '-std=c++0x' in the options.mk file. However the compiler will then print some warnings that PsiQuaSP uses features that are not supported by the c++98 standard. So far however there have been no issues with that, the performance was not affected. In the future we will try to resolve this problem in a more thorough way.
On Linux machines we have not encountered similar problems so far.
All the best,
Michael
